openapi: '3.0.3'
info:
  title: 교육정보 알리미
  version: '1.0'
tags: 
  - name: blacklist
    description: 블랙리스트 관련
  - name: board
    description: 게시판 관련
  - name: user
    description: 회원관련
  - name: login/out
  - name: popup
    description: 광고 팝업 관련
  - name: push
    description: 푸쉬 알람 관련
paths:
  /user/{email}:
    get:
      summary: "유저정보를 반환함 (수정 필요 : pw, location ,id, phone(- 빼기) )"
      tags: [user]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    format: email
                    example: myks790@gmail.com
                  nickname:
                    type: string
                    example: 닉네임
                  name:
                    type: string
                    example: 강모씨
                  phone:
                    type: string
                    example: '01012345678'
                  address:
                    type: string
                    example: 제주도 특별자치도 제주시 진남로 99길 10
                  detail adress:
                    type: string
                    example: 101호
                  role:
                    type: string
                    enum:
                      - 일반
                      - 인증
                      - 관리자
                    example: 인증
                  push agree:
                    type: string
                    enum:
                      - yes
                      - no
                    example: yes
                  email check:
                    type: string
                    enum:
                      - yes
                      - no
                    example: no
                  authuser_id:
                    type: integer
                    example: 1
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: error message

    put:
      summary: 유저 정보를 수정함 (개발중) 
      tags: [user]
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: error message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: 비밀번호
                nickname:
                  type: string
                  example: 닉네임
                phone:
                  type: string
                  example: 01012345678
                address:
                  type: string
                  example: 제주도 특별자치도 제주시 진남로 99길 10
                addressDetail:
                  type: string
                  example: 101호
                pushAgree:
                  type: boolean
                  example: true
    parameters:
      - name: email
        in: path
        required: true
        schema:
          type: string
        example: myks790@gmail.com
  
  /board/{boardId}:
    get:
      summary: 게시글을 반환함
      tags: [board]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: 여름 코딩 캠프
                  content:
                    type: string
                    example: "여름 14박 15일 코딩코딩코딩코딩딩딩딩 문의 : ~~~~"
                  writer:
                    type: string
                    example: 강상훈
                  location:
                    type: string
                    example: 제주특별자치도
                  start_date:
                    type: string
                    example: 2020-07-01T09:12:28Z
                  end_date:
                    type: string
                    example: 2020-08-31T07:12:28Z
      parameters:
        - name: boardId
          in: path
          required: true
          schema:
            type: integer
          example: 1
  
  /board:
    get:
      summary: 게시글 리스트를 반환함 (개발중, db auth 필드 필요(인증, 자유 게시판 여부),  locaion(id???),  major, target(code???) ) 
      tags: [board]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  contents:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        title:
                          type: string
                          example: 여름 코딩 캠프
                        writer:
                          type: string
                          example: 강상훈
                  pageNumber:
                    type: integer
                    example: 1
                  totalPages:
                    type: integer
                    example: 1
    parameters:
      - name: auth
        in: query
        required: true
        schema:
          type: boolean
        description: 인증 게시판, 자유 게시판 선택 플래그
        example: yes
      - name: page
        description: 'default: 1'
        in: query
        schema:
          type: integer
        example: 1
      - name: pageSize
        description: 'default: 10'
        in: query
        schema:
          type: integer
        example: 10
      - name: location
        in: query
        schema:
          type: string
        example: 제주특별자치도
      - name: major
        in: query
        schema:
          type: string
        description: "major code(001: '경영,회계,사무', 002: '취업,창업', 003: '금융,보험', ...)"
        example: "001"
      - name: target
        in: query
        schema:
          type: string
        description: "target code(001: 성인, 002: 유아, 003: 청소년)"
        example: "001"
  
  /board/major:
    get:
      tags: [board]
      summary: 대분류를 반환함
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 1
                    name:
                      type: string
                      example: 경영, 회계, 사무
  
  /board/location:
    get:
      tags: [board]
      summary: 시도 리스트를 반환함
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 1
                    name:
                      type: string
                      example: 서울특별시
  /blacklist:
    get:
      tags: [blacklist]
      summary: 블랙리스트 목록을 반환함 (개발중)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  contents:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        reporter:
                          type: string
                          format: email
                          example: myks790@gmail.com
                        reportedUser:
                          type: string
                          format: email
                          example: test@test.com
                        content:
                          type: string
                          example: 욕설등 부적절한 발언을 해서 신고합니다.
                        createdAt:
                          type: string
                          example: 2020-07-01T09:12:28Z
                        status:
                          type: string
                          enum:
                            - yes
                            - no
                            - waiting
                          example: waiting
                  pageNumber:
                    type: integer
                    example: 1
                  totalPages:
                    type: integer
                    example: 1
      parameters:
        - name: status
          description: 동의여부(대기, 동의, 거부)
          in: query
          schema:
            type: string
        - name: page
          description: 'default: 1'
          in: query
          schema:
            type: integer
          example: 1
        - name: pageSize
          description: 'default: 10'
          in: query
          schema:
            type: integer
          example: 10

    post:
      summary: 블랙리스트 추가 (개발중)
      tags: [blacklist]
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reporter:
                  type: string
                  format: email
                  example: myks790@gmail.com
                reportedUser:
                  type: string
                  format: email
                  example: spam@user.com
                content:
                  type: string
                  example: 욕설등 부적절한 발언을 해서 신고합니다.
                
  /blacklist/{blacklistId}:
    put:
      summary: 블랙리스트 status 수정 (개발중, db status 관련 수정 필요)
      tags: [blacklist]
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: 동의, 거부 만 선택 가능(기본값은 대기)
                  example: '거부'
  /popup:
    get:
      tags: [popup]
      summary: 홍보 팝업 조회 (개발중)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  image:
                    type: string
                    example: myks790.iptime.org/images/popup/asldfkjafs.png
                  active:
                    type: string
                    enum:
                      - yes
                      - no
                    example: yes

    post:
      summary: 광고 이미지 변경 (개발중)
      tags: [popup]
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                image:
                  type: string
                  example: myks790.iptime.org/images/popup/asldfkjafs.png
                
    put:
      summary: 팝업 활성화 설정 (개발중)
      tags: [popup]
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                active:
                  type: string
                  description: yes, no 만 선택 가능
                  example: 'yes'
                  enum:
                    - yes
                    - no



